In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
#  Step 1 : Create a synthetic classification dataset using slearn
x, y = make_classification(
    n_samples =10,      # Number of Samples
    n_features = 10,    # Number of features
    n_informative = 2,  # Number of informative features
    n_redundant = 0,    # Number of redundant features
    n_classes = 2,      # Number of classes
    random_state =42    # for reproductivity
)

In [ ]:
x

array([[-0.70205309, -1.46351495,  1.97686236, -0.39210815, -0.5297602 ,
         0.96864499, -2.8953973 ,  0.51326743,  0.09707755, -0.32766215],
       [-1.47852199,  1.05712223, -1.97171753, -0.46063877,  0.73846658,
        -0.3011037 , -0.58723065,  0.17136828, -0.11564828, -0.71984421],
       [ 0.36163603,  1.53803657, -0.97007347,  0.36139561,  0.81252582,
         1.0035329 ,  1.06833894,  1.35624003, -0.07201012, -0.64511975],
       [ 0.2088636 ,  0.19686124, -0.96059253, -1.32818605, -0.01349722,
        -1.22084365, -0.72063436, -1.05771093,  0.82254491, -1.95967012],
       [ 0.25755039, -0.02651388,  0.83444483, -1.91877122, -0.16128571,
         0.17457781,  1.89969252,  0.40405086,  1.8861859 , -0.07444592],
       [-0.676922  ,  0.93128012, -0.83879234,  1.03099952,  0.34361829,
        -0.38508228, -1.14021544, -1.76304016,  0.32408397,  0.61167629],
       [-1.41537074, -0.80227727,  1.51157598, -0.34271452,  0.29612028,
        -0.23458713,  1.77736657,  0.26105527

In [ ]:
X = torch.tensor(x,dtype = torch.float32)
y = torch.tensor(y,dtype = torch.long)

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features =features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):

    return self.features[index] , self.labels[index]

In [ ]:
dataset = CustomDataset(X,y)

In [ ]:
len(dataset)


10

In [ ]:
dataset[2]

(tensor([ 0.3616,  1.5380, -0.9701,  0.3614,  0.8125,  1.0035,  1.0683,  1.3562,
         -0.0720, -0.6451]),
 tensor(1))

In [ ]:
dataloader = DataLoader(dataset,batch_size=2,shuffle= True)

In [ ]:
for  batch_features,batch_labels in dataloader :
   print(batch_features)
   print(batch_labels)
   print("-"*80)


tensor([[-0.8085,  0.3288, -0.9923,  0.9154, -0.2197, -0.5183, -1.9629,  0.3571,
          1.4779, -0.5018],
        [ 0.0870, -1.9876, -1.1858,  0.0918, -0.0358,  0.8219,  1.7273,  1.5646,
         -2.6197, -0.2990]])
tensor([0, 1])
--------------------------------------------------------------------------------
tensor([[-1.4785,  1.0571, -1.9717, -0.4606,  0.7385, -0.3011, -0.5872,  0.1714,
         -0.1156, -0.7198],
        [-1.4154, -0.8023,  1.5116, -0.3427,  0.2961, -0.2346,  1.7774,  0.2611,
          0.0051, -0.4206]])
tensor([0, 1])
--------------------------------------------------------------------------------
tensor([[ 0.2089,  0.1969, -0.9606, -1.3282, -0.0135, -1.2208, -0.7206, -1.0577,
          0.8225, -1.9597],
        [-0.4792, -1.1962, -0.5430, -1.1063, -0.8392,  0.9755, -0.9382, -0.3092,
          0.3313, -0.1857]])
tensor([0, 1])
--------------------------------------------------------------------------------
tensor([[ 0.3616,  1.5380, -0.9701,  0.3614,  0.8125,  