In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.")

GPU not available.


In [ ]:
# crearting tensors

In [ ]:
# using empty
a =torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [ ]:
# use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# using arange
print(torch.arange(0,3,1))

# using linspace
print(torch.linspace(0,10,15))

# using eye
print(torch.eye(5))

# using full
print(torch.full((3,3),5))

tensor([0, 1, 2])
tensor([ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571,  3.5714,  4.2857,  5.0000,
         5.7143,  6.4286,  7.1429,  7.8571,  8.5714,  9.2857, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# shapes of tensors
a.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(a)

tensor([[2.6676e-14, 0.0000e+00, 2.0272e-14],
        [0.0000e+00, 2.3694e-38, 2.3694e-38]])

In [ ]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand_like(a,dtype = torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [ ]:
# tensor Data Types


In [ ]:
# find dtype
a.dtype

# assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
a.to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

# Inplace Operations


In [ ]:
# inplace operations

m  =torch.rand(2,3)
n  =torch.rand(2,3)
print(m)
print(n)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


In [ ]:
m+n

tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])

In [ ]:
m.add_(n)

tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])

In [ ]:
m

tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])

In [ ]:
m = torch.relu(m)

In [ ]:
m

tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])

# Copying tensor


In [ ]:
a = torch.rand(2,3)

In [ ]:
b =a

In [ ]:
a[0][0]  = 0

In [ ]:
b[0][0]

tensor(0.)

In [ ]:
print(id(a))
print(id(b))

133787815457808
133787815457808


In [ ]:
b = a.clone()

In [ ]:
a[0][1] = 5

In [ ]:
b[0][1]

tensor(0.2695)

# Mathematical Operations

In [ ]:
x = torch.rand(2,3)

In [ ]:
print(x+32)
print(x-2)
print(x*4)
print((x*8)//2)
print((x*7) %3)
print(x**2)

tensor([[32.3140, 32.1236, 32.8457],
        [32.3331, 32.2419, 32.6340]])
tensor([[-1.6860, -1.8764, -1.1543],
        [-1.6669, -1.7581, -1.3660]])
tensor([[1.2561, 0.4945, 3.3826],
        [1.3323, 0.9676, 2.5361]])
tensor([[1., 0., 3.],
        [1., 0., 2.]])
tensor([[2.1982, 0.8653, 2.9196],
        [2.3315, 1.6933, 1.4382]])
tensor([[0.0986, 0.0153, 0.7151],
        [0.1109, 0.0585, 0.4020]])


# Tesor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device  = torch.device('cuda')

In [ ]:
# creating a new tensor  on GPU
b  =torch.rand((2,3),device  = device)

In [ ]:
b+5

tensor([[5.5890, 5.1352, 5.0574],
        [5.4003, 5.1277, 5.3716]], device='cuda:0')

# Resahping Tensor

In [ ]:
a = torch.rand(4,4)

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[0.7514, 0.2059],
          [0.4915, 0.9476]],

         [[0.8745, 0.4017],
          [0.7536, 0.9907]]],


        [[[0.5359, 0.3088],
          [0.8413, 0.3048]],

         [[0.1917, 0.6543],
          [0.6905, 0.7827]]]])

In [ ]:
# flatten
a.flatten()


tensor([0.7514, 0.2059, 0.4915, 0.9476, 0.8745, 0.4017, 0.7536, 0.9907, 0.5359,
        0.3088, 0.8413, 0.3048, 0.1917, 0.6543, 0.6905, 0.7827])

In [ ]:
b = torch.rand(3,2,4)

In [ ]:
# permutee
b.permute(2,0,1).shape

torch.Size([4, 3, 2])

In [ ]:
# unsueeze
c = torch.rand(128,128,3)

c.unsqueeze(dim  = 0).shape

torch.Size([1, 128, 128, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and Pytorch

In [ ]:
import numpy as np
a  =torch.tensor([1,2,3])

In [ ]:
b =a.numpy()

In [ ]:
b


array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c  = np.array([1,2,3,4])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3, 4])

# Elemnt wise Operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)


tensor([[1.2303, 0.8858, 0.2598],
        [0.5789, 1.4788, 1.6162]])
tensor([[-0.2800,  0.2234, -0.2572],
        [ 0.5731,  0.3404, -0.3825]])
tensor([[3.5883e-01, 1.8367e-01, 3.3455e-04],
        [1.6778e-03, 5.1776e-01, 6.1641e-01]])
tensor([[6.2921e-01, 1.6745e+00, 5.0065e-03],
        [1.9774e+02, 1.5981e+00, 6.1724e-01]])
tensor([[0.4752, 0.2234, 0.0013],
        [0.0022, 0.3404, 0.6168]])
tensor([[0.5701, 0.8226, 0.1792],
        [0.9984, 0.9475, 0.6170]])


In [ ]:
c = torch.tensor([1,2,3,-2,-4,2,-6])


In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 2, 4, 2, 6])

In [ ]:
# neg
torch.neg(c)

tensor([-1, -2, -3,  2,  4, -2,  6])

In [ ]:
c = torch.tensor([1,2,3.8,-2.7,-4,2.3,-6.4])


In [ ]:
# round
torch.round(c)

tensor([ 1.,  2.,  4., -3., -4.,  2., -6.])

In [ ]:
torch.ceil(c)

tensor([ 1.,  2.,  4., -2., -4.,  3., -6.])

In [ ]:
torch.floor(c)

tensor([ 1.,  2.,  3., -3., -4.,  2., -7.])

In [ ]:
torch.clamp(c,min=-5,max = 5)

tensor([ 1.0000,  2.0000,  3.8000, -2.7000, -4.0000,  2.3000, -5.0000])

# Reduction Ooperations

In [ ]:
e = torch.randint(size= (2,3),low = 0, high =10,dtype =torch.float32)

In [ ]:
e


tensor([[3., 9., 1.],
        [7., 8., 3.]])

In [ ]:
# sum
print(torch.sum(e))
# sum along column
print(torch.sum(e,0))
# sum along rows
print(torch.sum(e,1))
# mean
print(torch.mean(e))

# mean along column
print(torch.mean(e,dim = 0))
# mean along rows
print(torch.mean(e,1))


# median
print(torch.median(e))

tensor(31.)
tensor([10., 17.,  4.])
tensor([13., 18.])
tensor(5.1667)
tensor([5.0000, 8.5000, 2.0000])
tensor([4.3333, 6.0000])
tensor(3.)


In [ ]:
# max min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
torch.prod(e)

tensor(4536.)

In [ ]:
# standard variance
print(torch.std(e))

# variance
print(torch.var(e))

tensor(3.2506)
tensor(10.5667)


In [ ]:
# argmax
print(torch.argmax(e))

# argmin
print(torch.argmin(e))

tensor(1)
tensor(2)


# Matrix Operations

In [ ]:
f = torch.tensor([1,2])
g = torch.tensor([[3,2],[4 ,5]])

In [ ]:
# matrix multiplication
torch.matmul(f,g)


tensor([11, 12])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,2])

In [ ]:
torch.dot(vector1,vector2)

tensor(7)

In [ ]:
torch.transpose(g,0,1)

tensor([[3, 4],
        [2, 5]])

In [ ]:
h  = g.clone()
h = h.to(torch.float32)

In [ ]:
# determinant
torch.det(h)

tensor(7.)

In [ ]:
torch.inverse(h)

tensor([[ 0.7143, -0.2857],
        [-0.5714,  0.4286]])

# Speacial Functions

In [ ]:
k = torch.randint(size = (2,3),low = 2, high = 10)

In [ ]:
# log
print(torch.log(k))

tensor([[2.1972, 2.0794, 1.9459],
        [1.7918, 0.6931, 1.3863]])


In [ ]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 2.9810e+03, 1.0966e+03],
        [4.0343e+02, 7.3891e+00, 5.4598e+01]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.8284, 2.6458],
        [2.4495, 1.4142, 2.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9997, 0.9991],
        [0.9975, 0.8808, 0.9820]])

In [ ]:
# relu
torch.relu(k)

tensor([[9, 8, 7],
        [6, 2, 4]])

In [ ]:
l  =k.to(torch.float32)

In [ ]:
# softmax
torch.softmax(l,dim= 0)

tensor([[0.9526, 0.9975, 0.9526],
        [0.0474, 0.0025, 0.0474]])